[phases.setup]
  nixPkgs = ['php84'] 

[phases.build]
  cmds = [
    'php -v',  # Debug: harus muncul PHP 8.4.x
    'composer install --optimize-autoloader --no-dev --no-interaction',
    'chmod +x railway/init-app.sh'
  ]

[start]
  cmd = "railway/init-app.sh && php artisan serve --host=0.0.0.0 --port=$PORT"
