[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.mbstring",
    "php82Extensions.pdo",
    "php82Extensions.pdo_pgsql",
    "php82Extensions.openssl",
    "php82Extensions.curl",
    "php82Extensions.fileinfo",
    "php82Extensions.gd",
    "php82Extensions.intl",
    "php82Extensions.zip",
    "nodejs-18_x"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist"
]

[phases.build]
cmds = [
    "npm ci && npm run build"
]

[start]
cmd = "./railway/init-app.sh && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
